### ISSUE TITLE
Conflict markers in FAQ

### ISSUE THREAD

**Issue by bburky** [IceCTF/ctf-landing#1]
You accidentally left some git conflict markers in faq.html during a merge:

https://github.com/IceCTF/ctf-landing/blob/2ec1023adfc64daf69a74a89ebc34bb2a19842ef/icectf/templates/faq.html#L98-L102

It's showing up on the site at https://icec.tf/faq.

**Comment by Glitch-is** [comment]
Thanks for the heads up!
